### ISSUE TITLE
Fatal error portaudio.h no such file or directory

### ISSUE THREAD

**Issue by bbookman** [blechdom/infinite-streaming-speech#1]
If I follow the instructions in [transcribe_streaming_infinite.py](https://github.com/blechdom/infinite-streaming-speech/blob/master/transcribe_streaming_infinite.py)
```
fatal error: portaudio.h: No such file or directory
     #include "portaudio.h"
```
After searching I resolved my issue by:

`sudo apt-get install python3-pyaudio`

I suggest you review and update your instructions on the prerequisites.  See this [StackOverflow post](https://stackoverflow.com/questions/33513522/when-installing-pyaudio-pip-cannot-find-portaudio-h-in-usr-local-include) also.

**Comment by bbookman** [comment]
Actually, even after doing the sudo apt-get, I still have an issue
`File "infinite_streaming.py", line 37, in <module>
    import pyaudio
ImportError: No module named 'pyaudio'`

**Comment by bbookman** [comment]
After even further searching for a solution to the dependency issue here, I got this error.  Not sure if pyaudio is truly installed correctly

`AttributeError: module 'pyaudio' has no attribute 'PyAudio'`

Note, I'm using python3.  If this code only supports python2, please indicate such

Also take a look at all the crazy troubleshooting for pyaudio: [Here](https://www.raspberrypi.org/forums/viewtopic.php?t=54658)

**Comment by bbookman** [comment]
Can't get it to work for Python 2.7 either.  Even after installing google-cloud for Python, I get this:

```
Traceback (most recent call last):
  File "infinite_streaming.py", line 36, in <module>
    from google.cloud import speech_v1p1beta1 as speech
ImportError: No module named google.cloud
```
